spring:
  application:
    name: webauthn-server

server:
  ssl:
#    certificate: "classpath:ssl/generated/public.crt"
    certificate-private-key: "classpath:ssl/generated/localhost-key.pem"
    trust-certificate: "classpath:ssl/generated/localhost.pem"
#    key-password: "0032c31b563d4667809a6a058f0e5528"
  port: 443

---
spring:
  config:
    activate:
      on-profile: local
