spring:
  application:
    name: webauthn-server

server:
  ssl:
    key-store: "classpath:ssl/generated/keystore.p12"
    key-store-type: "PKCS12"
    key-store-password: "password"
    enabled: true

---
spring:
  config:
    activate:
      on-profile: local
